apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: registry-admin-secret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    template:
      engineVersion: v2
      data:
        username: admin
        password: {{` "{{ .password }}" `}}
  data:
    - secretKey: password
      remoteRef:
        key: /registry/admin
        property: password
