---
- name: Install Cronie Package
  dnf:
    name: cronie
    state: present

- name: Set up FIRST WEEKLY reboot
  cron:
    name: First Weekly Reboot
    minute: 0
    hour: 2
    weekday: 1
    job: "/sbin/reboot"
    state: present

- name: Set up SECOND WEEKLY reboot
  cron:
    name: Second Weekly Reboot
    minute: 0
    hour: 2
    weekday: 5
    job: "/sbin/reboot"
    state: present

- name: Restart Cronie Service
  service:
    name: crond
    state: restarted