# SPDX-License-Identifier: MIT-0
---
# defaults file for create_virtual_machines

# Libvirt provider configuration
hypervisor_user: "{{ ansible_user }}"
hypervisor_host: "{{ hypervisor_address }}"  # Referencing the global variable
keyfile: "{{ ansible_ssh_private_key_file }}"
bridge_interface: "{{ bridge_interface }}"  # Referencing the global variable

# Storage configuration
storage_pool_path: "{{ storage_pool_path }}"
storage_pool_name: "{{ storage_pool_name }}"

# VM default configurations
default_memory: 16384
default_vcpu: 6
default_disk_size: 250
