apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: foodtrack
    argocd.argoproj.io/instance: foodtracker
  name: {{ .Release.Name }}-foodtrack
  namespace: {{ .Release.Namespace }}
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: foodtrack
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: foodtrack
    spec:
      containers:
        - name: foodtrack
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range $key, $value := .Values.secrets }}
            {{- if $value }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ index $.Values.deploymentAnnotations "operator.1password.io/item-name" }}
                  key: {{ $key }}
            {{- end }}
            {{- end }}
            - name: TZ
              value: {{ .Values.timezone | default "UTC" }}
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
