{{- range $index, $externalSecret := .Values.externalSecrets }}
{{- if $index }}
---
{{- end }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $externalSecret.name }}
spec:
  secretStoreRef:
    kind: {{ $externalSecret.secretStoreRef.kind }}
    name: {{ $externalSecret.secretStoreRef.name }}
  target:
    template:
      type: Opaque
  data:
  {{- range $secret := $externalSecret.data }}
    - secretKey: {{ $secret }}
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: {{ $secret }}
        metadataPolicy: None
        property: {{ $secret }}
  {{- end }}
{{- end }}
