apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: open-webui-oauth
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    name: open-webui-oauth
  data:
    - secretKey: client_secret
      remoteRef:
        key: dex.openwebui
        property: client_secret
