apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: open-webui-oauth
  namespace: {{ .Release.Namespace }}
spec:
  itemPath: vaults/z3emsr5qi5xqk33wthv5fpmfqa/items/rznaz276pelmmcgsvgyun4expy
