app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: registry.lajas.tech/vscode-tunnel
            tag: latest
            pullPolicy: Always
          env:
            TZ: "America/Chicago"
            TUNNEL_NAME: &host "sector-vsc"
            PROVIDER: "microsoft"
            PODMAN: "true"
            DOCKER: "true"
            DOCKER_COMPOSE: "true"
            OHMYZSH: "true"
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
  service:
    main:
      enabled: false
  persistence:
    data:
      accessMode: ReadWriteOnce
      size: 15Gi
      advancedMounts:
        main:
          main:
            - path: /home/coder
  defaultPodOptions:
    hostname: *host
    securityContext:
      fsGroup: 1000
