app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: registry.lajas.tech/code-tunnel
            tag: latest
            pullPolicy: Always
          env:
            TZ: "America/Chicago"
            TUNNEL_NAME: "SecretTunnel"
            PROVIDER: "microsoft"
        probes:
          liveness:
            enabled: false
          readiness:
            enabled: false
          startup:
            enabled: false    
      initContainers: []
  service:
    main:
      enabled: false
  persistence:
  #   data:
  #     accessMode: ReadWriteOnce
  #     size: 15Gi
  #     advancedMounts:
  #       main:
  #         main:
  #           - path: /home/coder
  #         backup:
  #           - path: /home/coder
  #         restore:
  #           - path: /home/coder
