# values.yaml for bolt-diy Helm chart using bjw-s common chart
# See https://github.com/bjw-s-labs/helm-charts/blob/main/charts/library/common/values.yaml for all options
app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: lscr.io/linuxserver/code-server
            tag: latest
            pullPolicy: Always
          env:
            PUID: "99"
            PGID: "100"
            PASSWORD:
              valueFrom:
                secretKeyRef:
                  name: "code-passwords"
                  key: "code-password"
            SUDO_PASSWORD:
              valueFrom:
                secretKeyRef:
                  name: "code-passwords"
                  key: "code-sudo-password"
            TZ: "America/Chicago"
      initContainers:
  service:
    main:
      ports:
        http:
          port: 8443
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host code.lajas.tech
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - hosts:
            - *host
          secretName: code-tls-certificate
  persistence:
    data:
      accessMode: ReadWriteOnce
      size: 15Gi
      advancedMounts:
        main:
          main:
            - path: /config

opSecrets:
  vault: "z3emsr5qi5xqk33wthv5fpmfqa"
  secrets:
    - name: code-secrets
      item: "k4a47koowgjxq7bdopufl2sjz4"
      secretName: "code-passwords"
