# Default values for rdtclient.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: rogerfar/rdtclient
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 2.0.49

service:
  type: ClusterIP
  port: 6500

securityContext:
  runAsUser: 911
  runAsGroup: 911

ingress:
  main:
    enabled: true
    ingressclassName: nginx
    annotations:
      certManagerClusterIssuer: letsencrypt-prod
      hajimariAppName: RDT-Client
      hajimariIcon: cloud-download
    host: rdclient.falconpunch.org
    path: /
    pathType: Prefix
    tls:
      secretName: rdtclient-tls-certificate
      host: rdclient.falconpunch.org

volumes:
  downloads:
    flexVolume:
      enabled: true
      name: flexvolume
      mountPath: /data/downloads
      driver: fstab/cifs
      fsType: cifs
      options:
        mountOptions: dir_mode=0755,file_mode=0644,noperm,nobrl
        networkPath: \\plex.falconpunch.org\downloads
      secretRef:
        name: smbcreds
  db:
    pvc:
      name: db-pvc
      mountPath: /data/db
      accessModes: ReadWriteOnce
      storageSize: 1Gi
