{{- $config := .Values.containers.unbound.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "unbound.fullname" . }}
  labels:
    app: {{ template "unbound.name" . }}
    chart: {{ template "unbound.chart" . }}
    release: {{ .Release.Name  }}
    heritage: {{ .Release.Service }}
data:
  unbound.conf: |-
    server:
      chroot: ""
      logfile: ""
      log-local-actions: {{ $config.logLocalActions | default "no" }}
      log-queries: {{ $config.logQueries | default "no" }}
      log-replies: {{ $config.logReplies | default "no" }}
      # log lines that say why queries return SERVFAIL to clients
      log-servfail: {{ $config.logServfail | default "no" }}
      verbosity: {{ $config.verbosity | default "1" }}
      log-tag-queryreply: yes

      num-threads: {{ $config.numThreads }}
      directory: "/etc/unbound"
      port: {{ .Values.containers.unbound.serverPort }}
      so-reuseport: yes
      do-daemonize: no
      use-syslog: no
      statistics-interval: {{ $config.statsInterval | default "0"}}
      statistics-cumulative: {{ $config.statsCumulative | default "no" }}

      auto-trust-anchor-file: "/var/lib/unbound/root.key"
      {{- if $config.rootHints.enable }}
      root-hints: {{ $config.rootHints.dir | quote }}
      {{- end }}
      do-ip4: {{ $config.doIp4 | default "yes" }}
      prefer-ip4: {{ $config.preferIp6 | default "yes" }}
      do-ip6: {{ $config.doIp6 | default "no" }}
      prefer-ip6: {{ $config.preferIp6 | default "no" }}
      # udp must be enabled because healthz nslookup ( busybox variant ) is not supporting tcp
      do-udp: yes
      do-tcp: {{ $config.doTcp }}
      tcp-upstream: {{ $config.tcpUpstream | default "yes" }}
      udp-upstream-without-downstream: {{ $config.udpUpstreamWithoutDownstream | default "no" }}

      prefetch: {{ $config.prefetch }}
      cache-max-ttl: {{ $config.cacheMaxTtl }}
      cache-max-negative-ttl: {{ $config.cacheMaxNegativeTtl }}
      cache-min-ttl: {{ $config.cacheMinTtl | default "0" }}

      extended-statistics: {{ $config.extendedStatistics | default "yes" }}

      interface: 127.0.0.1
      interface: 0.0.0.0

      access-control: 127.0.0.1/32 allow

      {{- range $config.allowedIpRanges }}
      access-control: {{ . }} allow
      {{- end }}{{ "\n" }}

      {{- range $config.privateAddresses }}
      private-address: {{ . }}
      {{- end }}

      {{- range $config.localRecords }}
      local-data: "{{ .name }} A {{ .ip }}"
      local-data-ptr: "{{ .ip }} {{ .name }}"
      {{- end }}

      local-data: "health.check.unbound A 127.0.0.1"
      local-data-ptr: "127.0.0.1 health.check.unbound"

      {{ with $config.extraServer }}
      {{- end }}

      {{- range $config.localZones }}
      local-zone: "{{ .name }}" {{ .localType }}
      {{- end }}
    remote-control:
      control-enable: {{ $config.controleEnable | default "yes" }}
      control-interface: {{ $config.controlInterface | default "127.0.0.1" }}
      control-port: {{ $config.controlPort | default "8953" }}
      control-use-cert: {{ $config.controlUseCert | default "no" }}

    {{- range $config.forwardZones }}
    forward-zone:
        name: {{ .name }}
        {{- range .forwardHosts }}
        forward-host: {{ . }}
        {{- end }}
        {{- range .forwardIps }}
        forward-addr: {{ . }}
        {{- end }}
    {{- end }}

    {{- range $config.stubZones }}
    stub-zone:
        name: {{ .name }}
        {{- range .stubHosts }}
        stub-host: {{ . }}
        {{- end }}
        {{- range .stubIps }}
        stub-addr: {{ . }}
        {{- end }}
    {{- end }}

    {{ with $config.extra }}
    {{- end }}
