apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "unbound.fullname" . }}
  labels:
    {{- include "unbound.labels" . | nindent 4 }}
    {{- with .Values.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{ end }}
  selector:
    matchLabels:
      {{- include "unbound.selectorLabels" . | nindent 6 }}
  {{- with .Values.updateStrategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "unbound.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
      - name: "unbound"
        image: {{ .Values.containers.unbound.image.repository }}:{{ .Values.containers.unbound.image.tag }}
        imagePullPolicy: {{ .Values.containers.unbound.image.pullPolicy | quote }}
        {{- with .Values.containers.unbound.resources }}
        resources: {{ toYaml . | nindent 10 }}
        {{- end }}
        ports:
        - name: "dns-tcp"
          containerPort: {{ .Values.containers.unbound.serverPort }}
          protocol: "TCP"
        {{- if .Values.service.udp.enabled }}
        - name: "dns-udp"
          containerPort: {{ .Values.containers.unbound.serverPort }}
          protocol: "UDP"
        {{- end }}
        volumeMounts:
        - name: "unbound-conf"
          mountPath: "/etc/unbound/"
          readOnly: true
        {{- with .Values.livenessProbe }}
        livenessProbe: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.readinessProbe }}
        readinessProbe: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.containers.unbound.args }}
        args: {{ toYaml . | nindent 10 }}
        {{- end }}
      - name: "healthz"
        image: {{ .Values.containers.healthz.image.repository }}:{{ .Values.containers.healthz.image.tag }}
        imagePullPolicy: {{ .Values.containers.healthz.image.pullPolicy | quote }}
        {{- with .Values.containers.healthz.resources }}
        resources: {{ toYaml . | nindent 10 }}
        {{- end }}
        args:
          - "-cmd=nslookup health.check.unbound. 127.0.0.1:{{ .Values.containers.unbound.serverPort }} > /dev/null"
        ports:
        - name: healthz
          containerPort: 8080
          protocol: TCP
      {{- if .Values.metrics.enabled }}
      - name: "exporter"
        image: {{ .Values.containers.exporter.image.repository }}:{{ .Values.containers.exporter.image.tag }}
        imagePullPolicy: {{ .Values.containers.exporter.image.pullPolicy | quote }}
        {{- with .Values.containers.exporter.resources }}
        resources: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.containers.exporter.args }}
        args: {{ toYaml . | nindent 10 }}
        {{- end }}
        ports:
        - name: metrics
          containerPort: 9167
          protocol: TCP
      {{- end }}
      volumes:
      - name: "unbound-conf"
        configMap:
          name: {{ template "unbound.fullname" . }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName | quote }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- if .Values.topologySpreadConstraints }}
      topologySpreadConstraints: {{ toYaml .Values.topologySpreadConstraints | nindent 8 }}
      {{- end }}
