{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: {{ include "unbound.pdb.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "unbound.fullname" . }}
  labels:
    {{- include "unbound.labels" . | nindent 4 }}
{{- with .Values.podDisruptionBudget.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "unbound.selectorLabels" . | nindent 6 }}
      {{- with .Values.labels }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
{{- end }}
