{{- if or ( .Values.service.tcp.enabled ) ( .Values.service.udp.enabled ) }}
kind: Service
apiVersion: v1
metadata:
  name: {{ template "unbound.fullname" . }}
  labels:
    {{- include "unbound.labels" . | nindent 4 }}
    {{- with .Values.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.service.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.service.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  selector:
    {{- include "unbound.selectorLabels" . | nindent 4 }}
    {{- with .Values.labels }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
  ports:
  {{- if .Values.service.udp.enabled }}
  - name: dns-udp
    protocol: UDP
    port: {{ .Values.containers.unbound.serverPort }}
    targetPort: dns-udp
  {{- end }}
  {{- if and ( eq .Values.containers.unbound.config.doTcp "yes" ) ( .Values.service.tcp.enabled )}}
  - name: dns-tcp
    protocol: TCP
    port: {{ .Values.containers.unbound.serverPort }}
    targetPort: dns-tcp
  {{- end }}
  {{- with .Values.service.sessionAffinity }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  {{- end }}
  {{- with .Values.service.sessionAffinityConfig }}
  sessionAffinityConfig: {{ toYaml . | nindent 2 }}
  {{- end }}
  {{- with .Values.service.topologyKeys }}
  topologyKeys: {{ toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
