---
apiVersion: v1
kind: Service
metadata:
  name: unbound-udp
  labels:
    {{- include "unbound-chart.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 8 }}
    {{- end }}
spec:
  {{- $type := default "LoadBalancer" .Values.service.type }}
  type: {{ $type }}
  {{- with .Values.service.spec }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: dns-udp
      protocol: UDP
      name: dns-udp
  selector:
    {{- include "unbound-chart.selectorLabels" . | nindent 4 }}
    app: pihole

---
apiVersion: v1
kind: Service
metadata:
  name: unbound-tcp
  labels:
    {{- include "unbound-chart.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 8 }}
    {{- end }}
spec:
  {{- $type := default "LoadBalancer" .Values.service.type }}
  type: {{ $type }}
  {{- with .Values.service.spec }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: dns-tcp
      protocol: TCP
      name: dns-tcp
  selector:
    {{- include "unbound-chart.selectorLabels" . | nindent 4 }}
    app: pihole
