apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: smb-credentials
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    template:
      type: fstab/cifs
  data:
  - secretKey: source
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: plex-smb-share
      property: serverPath
  - secretKey: username
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: plex-smb-share
      property: username
  - secretKey: password
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: plex-smb-share
      property: password
