apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistence.media.volumeName }}
  namespace: {{ .Release.Namespace }}
spec:
  capacity:
    storage: {{ .Values.persistence.media.size }}
  accessModes:
    - {{ .Values.persistence.media.accessMode }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: {{ .Values.persistence.media.nfs.server }}
    path: {{ .Values.persistence.media.nfs.path }}
  mountOptions:
    - hard
    - nfsvers=4.1
