replicaCount: 1

image:
  repository: mendhak/http-https-echo
  tag: "37"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  port: 8080

httpRoute:
  enabled: true
  name: header-echo
  host: headers.lajas.tech
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 128Mi
