apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-lab-access
  namespace: {{ .Release.Namespace }}
  labels:
    app: lab-access
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab-access
  template:
    metadata:
      labels:
        app: lab-access
    spec:
      containers:
      - name: {{ .Values.container.name }}
        image: "{{ .Values.container.image }}"
        env: {{- toYaml .Values.container.env | nindent 10 }}
