{{- $vault := .Values.opSecrets.vault }}

{{- range .Values.opSecrets.secrets }}
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .secretName }}
  namespace: {{ $.Release.Namespace }}
spec:
  itemPath: "vaults/{{ $vault }}/items/{{ .item }}"
{{- end }}
