router bgp 64512
 bgp router-id 10.137.0.1
 neighbor K8S peer-group
 neighbor K8S remote-as 64513
 neighbor 10.137.0.10 peer-group K8S
 neighbor 10.137.0.11 peer-group K8S
 neighbor 10.137.0.12 peer-group K8S
 neighbor METALLB peer-group
 neighbor METALLB remote-as 64514
 neighbor 10.137.0.13 peer-group METALLB
 neighbor 10.137.0.14 peer-group METALLB
 neighbor 10.137.0.15 peer-group METALLB
 neighbor 10.137.0.16 peer-group METALLB
 neighbor 10.137.0.17 peer-group METALLB
 address-family ipv4 unicast
  redistribute connected
  neighbor K8S activate
  neighbor K8S route-map ALLOW-ALL in
  neighbor K8S route-map ALLOW-ALL out
  neighbor K8S next-hop-self
  neighbor METALLB activate
  neighbor METALLB route-map ALLOW-ALL in
  neighbor METALLB route-map ALLOW-ALL out
  neighbor METALLB next-hop-self
  maximum-paths 8
 exit-address-family
!
route-map ALLOW-ALL permit 10
!
line vty
