apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "paperless-ai.fullname" . }}-config-file
  labels:
    {{- include "paperless-ai.labels" . | nindent 4 }}
data:
  config.js: |
    {{- (.Files.Get "files/config.js") | nindent 4 }}
