apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "paperless-ai.fullname" . }}-env-file
  labels:
    {{- include "paperless-ai.labels" . | nindent 4 }}
data:
  .env: {{ include "generateEnv" . | b64enc }}
