{{- if .Values.openAi.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "paperless-ai.fullname" . }}-open-ai-api
  labels:
    {{- include "paperless-ai.labels" . | nindent 4 }}
type: Opaque
data:
  OPENAI_API_KEY: {{ .Values.openAi.apiKey  | b64enc | quote }}
{{- end }}
