{{- if .Values.paperless.apiToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "paperless-ai.fullname" . }}-paperless-api
  labels:
    {{- include "paperless-ai.labels" . | nindent 4 }}
type: Opaque
data:
  PAPERLESS_API_TOKEN: {{ .Values.paperless.apiToken  | b64enc | quote }}
{{- end }}
