apiVersion: v2
name: plex-apps
description: A Helm chart for Plex applications
type: application
version: 0.1.0
appVersion: 1.16.0
dependencies:
  - name: plex-smb-share
    version: 0.1.0
    repository: "file://./charts/plex-smb-share"
  - name: radarr
    version: 16.3.2
    repository: "file://./charts/radarr"
  - name: prowlarr
    version: 4.5.2
    repository: "file://./charts/prowlarr"
  - name: rdtclient
    version: 0.1.0
    repository: "file://./charts/rdtclient"
  - name: sonarr
    version: 16.3.2
    repository: "file://./charts/sonarr"
  - name: overseerr
    version: 5.4.2
    repository: "file://./charts/overseerr"
