image:
  repository: registry.lajas.tech/geyser-mc
  tag: latest
replicaCount: 1
config:
  bedrock:
    port: 19132
geyser:
  enabled: true
  loadBalancerIP: "10.137.0.248"
  port: 19132
  # Additional Geyser-specific configurations as needed
  config:
    bedrock:
      # The port that will listen for connections
      port: 19132
      # This option makes the Bedrock port the same as the Java port every time you start the server.
      cloneRemotePort: false
      # The MOTD that will be broadcasted to Minecraft: Bedrock Edition clients
      motd1: "A Super Secret JAVA Server"
      motd2: "Brought to you by Geyser-MC!"
      # The Server Name that will be sent to Minecraft: Bedrock Edition clients
      serverName: "Bluffcraft.lajas.tech"
      # How much to compress network traffic to the Bedrock client.
      compressionLevel: 6
      # Whether to enable PROXY protocol or not for clients.
      enableProxyProtocol: false
    remote:
      # The IP address of the remote (Java Edition) server - Can be a FQDN if available!
      address: "bluffcraft.lajas.tech"
      # The port of the remote (Java Edition) server
      port: 25565
      # Authentication type. Can be offline, online, or floodgate
      authType: "online"
      # Maximum amount of players that can connect
      maxPlayers: 100
      # If debug messages should be sent through console
      debugMode: false
      # Allow for password-based authentication methods through Geyser.
      allowPasswordAuthentication: true
      # Whether to enable PROXY protocol or not while connecting to the server.
      useProxyProtocol: false
      # Forward the hostname that the Bedrock client used to connect over to the Java server
      forwardHostname: false
      # Stores a list of Bedrock players that should have their Java Edition account saved after login
    savedUserLogins:
      - SpecOp eX
      - Aliizsa
    # Specify how many seconds to wait while user authorizes Geyser to access their Microsoft account.
    pendingAuthenticationTimeout: 120
    # Bedrock clients can freeze when opening up the command prompt for the first time if given a lot of commands.
    commandSuggestions: true
    # Relay the MOTD from the remote server to Bedrock players.
    passthroughMotd: true
    # Relay the player count and max players from the remote server to Bedrock players.
    passthroughPlayerCounts: true
    # Enable LEGACY ping passthrough.
    legacyPingPassthrough: false
    # How often to ping the remote server, in seconds.
    pingPassthroughInterval: 3
    # Whether to forward player ping to the server.
    forwardPlayerPing: false
    # Maximum amount of players that can connect.
    maxPlayers: 100
    # If debug messages should be sent through console
    debugMode: false
    # Allow third party capes to be visible.
    allowThirdPartyCapes: false
    # Allow third party deadmau5 ears to be visible.
    allowThirdPartyEars: false
    # Allow a fake cooldown indicator to be sent.
    showCooldown: "title"
    # Controls if coordinates are shown to players.
    showCoordinates: true
    # Whether Bedrock players are blocked from performing their scaffolding-style bridging.
    disableBedrockScaffolding: false
    # If set, when a Bedrock player performs any emote, it will swap the offhand and mainhand items.
    emoteOffhandWorkaround: "disabled"
    # Specify how many days images will be cached to disk.
    cacheImages: 0
    # Allows custom skulls to be displayed.
    allowCustomSkulls: true
    # The maximum number of custom skulls to be displayed per player.
    maxVisibleCustomSkulls: 128
    # The radius in blocks around the player in which custom skulls are displayed.
    customSkullRenderDistance: 32
    # Whether to add any items and blocks which normally does not exist in Bedrock Edition.
    addNonBedrockItems: true
    # Bedrock prevents building and displaying blocks above Y127 in the Nether.
    aboveBedrockNetherBuilding: true
    # Force clients to load all resource packs if there are any.
    forceResourcePacks: true
    # Allows Xbox achievements to be unlocked.
    xboxAchievementsEnabled: false
    # Whether player IP addresses will be logged by the server.
    logPlayerIpAddresses: true
    # Whether to alert the console and operators that a new Geyser version is available.
    notifyOnNewBedrockUpdate: true
    # Which item to use to mark unavailable slots in a Bedrock player inventory.
    unusableSpaceBlock: "minecraft:barrier"
    metrics:
      # If metrics should be enabled - Not recommended as you'll need to
      # obtain the server uuid first and fill out the below key/value for it to work properly!
      enabled: false
      # UUID of server, don't change unless doing so as recommended above!
      uuid: ""
    # ADVANCED OPTIONS - DO NOT TOUCH UNLESS YOU KNOW WHAT YOU ARE DOING!
    # Geyser updates the Scoreboard after every Scoreboard packet, but when Geyser tries to handle
    # a lot of scoreboard packets per second can cause serious lag.
    # This option allows you to specify after how many Scoreboard packets per seconds
    # the Scoreboard updates will be limited to four updates per second.
    scoreboardPacketThreshold: 20
    # Allow connections from ProxyPass and Waterdog.
    # See https://www.spigotmc.org/wiki/firewall-guide/ for assistance - use UDP instead of TCP.
    enableProxyConnections: false
    # The internet supports a maximum MTU of 1492 but could cause issues with packet fragmentation.
    # 1400 is the default.
    mtu: 1400
    # Whether to connect directly into the Java server without creating a TCP connection.
    # This should only be disabled if a plugin that interfaces with packets or the network does not work correctly with Geyser.
    # If enabled on plugin versions, the remote address and port sections are ignored
    # If disabled on plugin versions, expect performance decrease and latency increase
    useDirectConnection: true
    # Whether Geyser should attempt to disable compression for Bedrock players. This should be a benefit as there is no need to compress data
    # when Java packets aren't being handled over the network.
    # This requires use-direct-connection to be true.
    disableCompression: true
    configVersion: 4
minecraft:
  sharedIPKey: "minecraft"
