apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dex-secrets
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    name: dex-secrets
  data:
    # Connectors
    - secretKey: KANIDM_CLIENT_ID
      remoteRef:
        key: kanidm.dex
        property: client_id
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: KANIDM_CLIENT_SECRET
      remoteRef:
        key: kanidm.dex
        property: client_secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None

    # Clients
    - secretKey: GRAFANA_SSO_CLIENT_SECRET
      remoteRef:
        key: dex.grafana
        property: client_secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: GITEA_CLIENT_SECRET
      remoteRef:
        key: dex.gitea
        property: client_secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: OPEN_WEBUI_CLIENT_SECRET
      remoteRef:
        key: dex.openwebui
        property: client_secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
