# Default values for byparr.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

env:
  - PUID: 1000
  - PGID: 1000
  - TZ: "America/Chicago"
  - USE_HEADLESS: default
  

image:
  repository: ghcr.io/thephaseless/byparr
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 2

replicaCount: 1

strategy:
  type: Recreate # Change to Recreate if you want to use the Recreate strategy
  rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 25%

service:
  type: ClusterIP
  port: 8191

ingress:
  main:
    enabled: true
    ingressclassName: nginx
    annotations:
      certManagerClusterIssuer: letsencrypt-prod
    host: &host byparr.lajas.tech
    path: /
    pathType: Prefix
    tls:
      secretName: byparr-tls-certificate
      host: *host

