apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: unifi-poller-secret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    template:
      type: Opaque
  data:
  - secretKey: unifiPassword
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: unpoller.user
      property: password
      metadataPolicy: None
