image:
  repository: tccr.io/truecharts/radarr
  pullPolicy: IfNotPresent
  tag: 4.4.4.7068@sha256:299a9fc534456ac607bb99e480582d413a8accc21b641f2041d7bcb30905ff26
service:
  main:
    ports:
      main:
        port: 7878
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            readiness:
              enabled: true
              type: http
              path: /ping
            liveness:
              enabled: true
              type: http
              path: /ping
            startup:
              enabled: true
              type: http
              path: /ping

          env:
            RADARR__PORT: "{{ .Values.service.main.ports.main.port }}"
