descheduler:
  deschedulerPolicy:
    profiles:
      - name: default
        pluginConfig:
          - name: RemovePodsViolatingNodeAffinity
            args:
              nodeAffinityType:
                - requiredDuringSchedulingIgnoredDuringExecution
          - name: RemovePodsViolatingNodeTaints
            args: {}
          - name: RemovePodsViolatingInterPodAntiAffinity
            args: {}
        plugins:
          deschedule:
            enabled:
              - RemovePodsViolatingNodeTaints
              - RemovePodsViolatingNodeAffinity
              - RemovePodsViolatingInterPodAntiAffinity
