apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Values.persistence.data.secret.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  itemPath: "vaults/{{ .Values.persistence.data.secret.vault }}/items/{{ .Values.persistence.data.secret.items }}"
