---
apiVersion: v2
appVersion: 1.17.4
description: Paperless - Index and archive all of your scanned paper documents
name: paperless
version: 9.1.3
kubeVersion: ">=1.16.0-0"
keywords:
  - paperless
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/paperless
icon: https://avatars.githubusercontent.com/u/47271576?s=200&v=4
sources:
  - https://github.com/paperless-ngx/paperless-ngx
maintainers:
  - name: mr-onion-2
  - name: jonnobrow
    email: jonathan@jonnobrow.co.uk
  - name: morremeyer
    email: charts@mor.re
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
  - name: postgresql
    version: 13.2.24
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 18.5.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 4.5.2
