apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dex.planka
  namespace: global-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: global-secrets
    kind: ClusterSecretStore
  target:
    name: dex.planka
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
  data:
  - secretKey: client_id
    remoteRef:
      key: admin-secrets
      property: clientId
  - secretKey: client_secret
    remoteRef:
      key: admin-secrets
      property: clientSecret
