- name: Start PXE server
  hosts: localhost
  roles:
    - pxe_server

- name: Setup virtual machines
  hosts: localhost
  pre_tasks:
    - name: Check for virtual machines in inventory
      set_fact:
        has_virtual_machines: >-
          {{
            groups['metal'] | map('extract', hostvars)
            | selectattr('virtual', 'defined')
            | selectattr('virtual', 'equalto', true)
            | list | length > 0
          }}

    - name: Check for virtual machines with GPUs in inventory
      set_fact:
        has_gpu_nodes: >-
          {{
            groups['metal'] | map('extract', hostvars)
            | selectattr('gpu_type', 'defined')
            | list | length > 0
          }}

  tasks:
    - import_role:
        name: virtualization
        tasks_from: boot

- name: Provision bare metal machines
  hosts: metal
  gather_facts: false
  roles:
    - wake
