- name: Install OS Packages on virtual machines
  hosts: metal
  gather_facts: true

  tasks:
    - import_role:
        name: virtualization
        tasks_from: cluster

- name: Create Kubernetes cluster
  hosts: metal
  roles:
    - k3s
    - automatic_upgrade
    - nfs_utils
    - cronjobs
