- name: Install OS Packages on virtual machines
  hosts: metal
  gather_facts: true

  roles:
    - role: vm_install_packages
      when: hostvars[inventory_hostname].virtual | default(false)

    - role: gpu_install_drivers
      when: hostvars[inventory_hostname].gpu_type is defined

- name: Create Kubernetes cluster
  hosts: metal
  roles:
    - k3s
    - automatic_upgrade
    - nfs_utils
    - cronjobs
