metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 10.137.0.10, mac: '00:23:24:ab:92:cb', disk: sda, network_interface: eno1}
        metal1: {ansible_host: 10.137.0.11, mac: '00:23:24:ab:8e:05', disk: sda, network_interface: eno1}
        metal2: {ansible_host: 10.137.0.12, mac: '00:23:24:ce:3a:53', disk: sda, network_interface: eno1}
    workers:
      hosts:
        metal3: {ansible_host: 10.137.0.13, mac: '00:23:24:ab:99:b9', disk: sda, network_interface: eno1}
