metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 10.137.0.10, mac: '00:23:24:ab:92:cb', disk: sda, network_interface: eno1}
        metal1: {ansible_host: 10.137.0.11, mac: '00:23:24:ab:8e:05', disk: sda, network_interface: eno1}
        metal2: {ansible_host: 10.137.0.12, mac: '00:23:24:ce:3a:53', disk: sda, network_interface: eno1}
        metal7: {ansible_host: 10.137.0.17, mac: '52:54:00:34:2a:c2', disk: sda, network_interface: enp12s0}
    workers:
      hosts:
        metal3: {ansible_host: 10.137.0.13, mac: '00:23:24:ab:99:b9', disk: sda, network_interface: eno1}
        metal4: {ansible_host: 10.137.0.14, mac: '6c:4b:90:3e:58:61', disk: sda, network_interface: enp0s31f6}
        metal5: {ansible_host: 10.137.0.15, mac: '6c:4b:90:6f:32:b1', disk: sda, network_interface: enp0s31f6}
        metal6: {ansible_host: 10.137.0.16, mac: 'd8:cb:8a:bf:d6:79', disk: vda, network_interface: ens2}
