metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 10.137.0.10, mac: '00:23:24:ab:92:cb', disk: sda, network_interface: eno1}
        metal1: {ansible_host: 10.137.0.11, mac: '00:23:24:ab:8e:05', disk: sda, network_interface: eno1}
        metal2: {ansible_host: 10.137.0.12, mac: '00:23:24:ce:3a:53', disk: sda, network_interface: eno1}
    workers:
      hosts:
        metal3: {ansible_host: 10.137.0.13, mac: '00:23:24:ab:99:b9', disk: sda, network_interface: eno1}
        metal4: {ansible_host: 10.137.0.14, mac: '6c:4b:90:3e:58:61', disk: sda, network_interface: enp0s31f6}
        metal5: {ansible_host: 10.137.0.15, mac: '6c:4b:90:6f:32:b1', disk: sda, network_interface: enp0s31f6}
        metal6: {ansible_host: 10.137.0.16, mac: '52:54:00:dd:1b:5f', disk: vda, network_interface: ens2, virtual: true, gpu_type: 'GeForce RTX 2060'}
        metal7: {ansible_host: 10.137.0.17, mac: '52:54:00:34:2a:c2', disk: vda, network_interface: ens1, virtual: true}
        metal8: {ansible_host: 10.137.0.18, mac: '52:54:00:34:2a:c4', disk: vda, network_interface: ens1, virtual: true}
