apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mylar-ingress
  labels:
    app: mylar
    app.kubernetes.io/name: mylar
    app.kubernetes.io/instance: mylar
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    hajimari.io/appName: Mylar
    hajimari.io/icon: surround-sound
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - mylar.eaglepass.io
      secretName: mylar-tls-certificate
  rules:
    - host: mylar.eaglepass.io
      http:
        paths:
          - path: /
            backend:
              service:
                name: mylar-service
                port:
                  name: http
            pathType: Prefix

---
apiVersion: v1
kind: Service
metadata:
  name: mylar-service
  labels:
    app: mylar
    app.kubernetes.io/name: mylar
    app.kubernetes.io/instance: mylar
spec:
  type: ClusterIP
  externalTrafficPolicy:
  ports:
    - name: http
      port: 8090
      targetPort: http
      protocol: TCP
  selector:
    app: mylar

---
apiVersion: v1
kind: Service
metadata:
  name: mylar-connect
  labels:
    app: mylar
    app.kubernetes.io/name: mylar
    app.kubernetes.io/instance: mylar
spec:
  clusterIP: 10.43.10.230
  ports:
    - name: http
      port: 8090
      targetPort: 8090
      protocol: TCP
  selector:
    app: mylar
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mylar-deployment
  labels:
    app: mylar
  namespace: mylar
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mylar
  template:
    metadata:
      labels:
        app: mylar
    spec:
      nodeName: pikachu
      containers:
        - name: mylar
          image: ghcr.io/linuxserver/mylar3:latest
          volumeMounts:
            - name: config
              mountPath: /config
            - name: backup-config
              mountPath: /config/Backups
            - name: downloads
              mountPath: /downloads
            - name: comics
              mountPath: /comics
          env:
            - name: PUID
              value: "99"
            - name: PGID
              value: "100"
            - name: LANGUAGE
              value: en_US.UTF-8
            - name: TZ
              value: America/Chicago
          ports:
            - name: http
              containerPort: 8090
      volumes:
        - name: backup-config
          nfs:
            server: 10.0.50.3
            path: /mnt/user/mylar_backups
        - name: config
          hostPath:
            path: /mylar/config
        - name: downloads
          nfs:
            server: 10.0.50.3
            path: /mnt/user/downloads
        - name: comics
          nfs:
            server: 10.0.50.3
            path: /mnt/user/comics