apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: backup-target
value: cifs://nas-01.storage.lajas.tech/longhorn_backup
---
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: backup-target-credential-secret
value: longhorn-backup-creds
