apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: backup-target
value: cifs://storage.lajas.tech/pvc
---
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: backup-target-credential-secret
value: longhorn-backup-creds
