apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cifs-creds
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    template:
      type: fstab/cifs
  data:
  - secretKey: source
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: /plex-smb-share
      property: serverPath
  - secretKey: CIFS_USERNAME
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: /plex-smb-share
      property: username
  - secretKey: CIFS_PASSWORD
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: /plex-smb-share
      property: password
