apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: longhorn-backup-creds
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    template:
      type: fstab/cifs
  data:
  - secretKey: CIFS_USERNAME
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: plex-smb-share
      property: username
      metadataPolicy: None
  - secretKey: CIFS_PASSWORD
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: plex-smb-share
      property: password
      metadataPolicy: None
