apiVersion: v1
kind: Service
metadata:
  name: {{ include "rdtclient.fullname" . }}
  labels:
    {{- include "rdtclient.labels" . | nindent 4 }}
  annotations:
spec:
  type: ClusterIP
  ports:
    - port: 6500
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "rdtclient.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
