apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: webhook-secret
  namespace: tekton-workflows
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  data:
    - secretKey: token
      remoteRef:
        key: /tekton/webhook
        property: token
