apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: webhook-secret
  namespace: tekton-workflows
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  data:
    - secretKey: token
      remoteRef:
        key: tekton.webhook
        property: token
