{{- if and .Values.turn.enabled .Values.turn.onePasswordItem.enabled }}
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Values.turn.onePasswordItem.secretName }}
  namespace: {{ include "moonlight-web.namespace" . }}
spec:
  itemPath: "vaults/{{ .Values.turn.onePasswordItem.vault }}/items/{{ .Values.turn.onePasswordItem.item }}"
{{- end }}
