gitea:
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      hajimari.io/appName: Gitea
      hajimari.io/icon: git
    hosts:
      - host: &host git.falconpunch.org
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: gitea-tls-certificate
        hosts:
          - *host
  gitea:
    admin:
      existingSecret: gitea-admin-secret
    config:
      server:
        LANDING_PAGE: explore
        ROOT_URL: https://git.falconpunch.org
      webhook:
        ALLOWED_HOST_LIST: private
  persistence:
    storageClass: longhorn
  postgresql:
    enabled: true
    persistence:
      storageClass: longhorn
  postgresql-ha:
    enabled: false
  redis-cluster:
    cluster:
      nodes: 6
