apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: homelab
spec:
  workspaces:
    - name: shared-data
  tasks:
    - name: git-clone
      taskRef:
        resolver: hub
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: version
            value: "0.7"
      workspaces:
        - name: output
          workspace: shared-data
      params:
        - name: url
          value: http://gitea-http.gitea:3000/ops/homelab
        - name: revision
          value: master
    - name: pre-commit
      workspaces:
        - name: source
          workspace: shared-data
      taskSpec:
        workspaces:
          - name: source
        stepTemplate:
          image: nixos/nix:latest
          workingDir: /workspace/source
        steps:
          - name: run
            command:
              - nix-shell
              - --command
            args:
              - "pre-commit run --color=always"
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: homelab
spec:
  serviceAccountName: tekton-admin
  pipelineRef:
    name: homelab
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
