apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pull-request
spec:
  workspaces:
    - name: shared-data
  tasks:
    - name: clone
      taskRef:
        resolver: hub
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: version
            value: "0.7"
      workspaces:
        - name: output
          workspace: shared-data
      params:
        - name: url
          value: $(params.git_url)
        - name: revision
          value: $(params.git_revision)
    - name: test
      workspaces:
        - name: source
          workspace: shared-data
      taskSpec:
        workspaces:
          - name: source
        stepTemplate:
          image: nixos/nix:latest
          workingDir: /workspace/source
        steps:
          # TODO optimize Nix cache, this is too slow
          - name: pre-commit
            command:
              - nix-shell
              - --command
            args:
              - "pre-commit run --color=always"
