apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.clusterRoleBinding.name }}
  labels:
    {{- include "monero-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: {{ .Values.clusterRoleBinding.roleRef.apiGroup }}
  kind: {{ .Values.clusterRoleBinding.roleRef.kind }}
  name: {{ .Values.clusterRoleBinding.roleRef.name }}
subjects:
  {{- range .Values.clusterRoleBinding.subjects }}
  - kind: {{ .kind }}
    name: {{ .name }}
    namespace: {{ .namespace }}
  {{- end }}
