apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ddns-cronjob
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: ddns-container
              image: registry.lajas.tech/ddns:Latest
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure

