apiVersion: batch/v1
kind: CronJob
metadata:
  name: ddns-cronjob
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: ddns-container
              image: llajas/ddns:latest
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
