apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ddns-secrets
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    name: ddns-updater-secrets
    template:
      type: Opaque
  data:
    - secretKey: CLOUDFLARE_API_KEY
      remoteRef:
        key: ddns.config
        property: cloudflareApiKey
    - secretKey: CLOUDFLARE_EMAIL
      remoteRef:
        key: ddns.config
        property: cloudflareEmail
    - secretKey: DOMAIN_NAME
      remoteRef:
        key: ddns.config
        property: domainName
    - secretKey: DNS_RECORD
      remoteRef:
        key: ddns.config
        property: dnsRecord
