apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: unifibrowser-secrets
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    template:
      type: Opaque  # Change this based on your needs
  data:
  - secretKey: USER
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: unifibrowser-secrets
      property: USER
  - secretKey: PASSWORD
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: unifibrowser-secrets
      property: PASSWORD
  - secretKey: UNIFIURL
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: unifibrowser-secrets
      property: UNIFIURL
  - secretKey: APIBROWSERPASS
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: unifibrowser-secrets
      property: APIBROWSERPASS
  - secretKey: APIBROWSERUSER
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: unifibrowser-secrets
      property: APIBROWSERUSER
