apiVersion: v1
kind: Service
metadata:
  name: {{ include "unifi-browser.fullname" . }}
  labels:
    {{- include "unifi-browser.labels" . | nindent 4 }}
  annotations:
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "unifi-browser.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
