apiVersion: k8up.io/v1
kind: Schedule
metadata:
  name: schedule-test
spec:
  backend:
    s3:
      endpoint: s3.us-east-005.backblazeb2.com
      bucket: llajas-homelab-backup
      accessKeyIDSecretRef:
        name: backblaze-credentials
        key: application-key-id
      secretAccessKeySecretRef:
        name: backblaze-credentials
        key: application-key
    repoPasswordSecretRef:
      name: backblaze-credentials
      key: repo-password
  backup:
    schedule: '0 8 * * *'
    failedJobsHistoryLimit: 2
    successfulJobsHistoryLimit: 2
    # TODO
    #promURL: https://prometheus:8443
  check:
    schedule: '0 1 * * 1'
    #promURL: https://prometheus:8443
  prune:
    schedule: '0 1 * * 0'
    retention:
      keepLast: 5
      keepDaily: 14
