apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Pipeline
  - https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml
  # Triggers
  - https://storage.googleapis.com/tekton-releases/triggers/latest/release.yaml
  - https://storage.googleapis.com/tekton-releases/triggers/latest/interceptors.yaml
  # Workflow
  - https://storage.googleapis.com/tekton-releases-nightly/workflows/latest/release.yaml
  # Dashboard
  - https://storage.googleapis.com/tekton-releases/dashboard/latest/tekton-dashboard-release.yaml
  - ingress.yaml
  # Service account
  - serviceaccount.yaml
  - clusterrolebinding.yaml
