apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pihole-admin-secret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    template:
      type: Opaque
  data:
  - secretKey: adminPassword
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: /pihole
      property: password
