#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: ghcr.io/onedr0p/prowlarr
  # @default -- chart.appVersion
  tag:
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables.
# @default -- See below
env:
  # -- Set the container timezone
  TZ: America/Chicago
    #  PUID: "1000"
    #PGID: "1000"

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 9696

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      hajimari.io/appName: Prowlarr
      hajimari.io/icon: paw
    hosts:
      - host: &host prowlarr.lajas.tech
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: prowlarr-tls-certificate
        hosts:
          - *host

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: true
    existingClaim: ""
    storageClassName: "longhorn"

  media:
    enabled: true
    existingClaim: "plex-win-pvc"
    mountPath: /media

securityContext:
  runAsUser: 568

podSecurityContext:
  fsGroup: 568

flexVolume:
  enabled: true
  name: flexvolume
  mountPath: /plexmedia
  driver: fstab/cifs
  fsType: cifs
  options:
    mountOptions: dir_mode=0755,file_mode=0644,noperm,nobrl
    networkPath: \\plex.lajas.tech\media
  secretRef:
    name: smbcreds
