apiVersion: v1
kind: Service
metadata:
  name: {{ include "cleanuparr.fullname" . }}-service
  labels:
    {{- include "cleanuparr.labels" . | nindent 4 }}
  annotations:
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Chart.Name }}
      protocol: TCP
      name: {{ .Chart.Name }}
  selector:
    app.kubernetes.io/name: {{ include "cleanuparr.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
