{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "tautulli.fullname" . }}-config
  labels:
{{ include "tautulli.labels" . | indent 4 }}
  annotations:
{{ toYaml .Values.persistence.annotations | indent 4 }}
spec:
  accessModes:
{{ toYaml .Values.persistence.accessModes | indent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  storageClassName: {{ .Values.persistence.storageClassName }}
{{- end }}

---
{{- if and .Values.persistence.logs.enabled (not .Values.persistence.logs.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "tautulli.fullname" . }}plex-logs
  labels:
{{ include "tautulli.labels" . | indent 4 }}
  annotations:
{{ toYaml .Values.persistence.logs.annotations | indent 4 }}
spec:
  accessModes:
{{ toYaml .Values.persistence.logs.accessModes | indent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.logs.size | quote }}
  storageClassName: {{ .Values.persistence.logs.storageClassName | quote }}
  volumeName: {{ .Values.persistence.logs.volumeName }}
{{- end }}
