# Container image
image:
  repository: registry.lajas.tech/soleless-app
  tag: latest
  pullPolicy: Always

opSecret:
  vault: "z3emsr5qi5xqk33wthv5fpmfqa"
  item: "4uvjmvioanbh3zknyg7buw6lkm"

settings:
  maxWorkers: 2
  maxRetries: 5
  retryDelay: 5
  taskPollInterval: 10
  taskTimeout: 1800
  batchSize: 10
