{{- $vault := .Values.opSecrets.vault }}
{{- range $key, $value := .Values.opSecrets }}
{{- if ne $key "vault" }}
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ $value.secretName }}
  namespace: {{ $.Release.Namespace }}
spec:
  itemPath: "vaults/{{ $vault }}/items/{{ $value.item }}"
{{- end }}
{{- end }}
