apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
spec:
  itemPath: "vaults/{{ .Values.opSecret.vault }}/items/{{ .Values.opSecret.item }}"
