external-dns:
  provider: pihole
  env:
    - name: EXTERNAL_DNS_PIHOLE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: pihole-admin-secret
          key: adminPassword
  extraArgs:
    - --pihole-server=http://pihole-web.pihole.svc.cluster.local
  interval: 24h
  triggerLoopOnEvent: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
