harbor:
  expose:
    ingress:
      hosts:
        core: registry.lajas.tech
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
    tls:
      certSource: secret
      secret:
        secretName: harbor-tls-certificate
        notarySecretName: notary-tls-certificate
  externalURL: https://registry.lajas.tech
  trivy:
    enabled: false
  notary:
    enabled: false
  persistence:
    enabled: true
    persistentVolumeClaim:
      registry:
        storageClass: longhorn
      jobservice:
        storageClass: longhorn
      database:
        storageClass: longhorn
      redis:
        storageClass: longhorn
