apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rdtclient.fullname" . }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ include "rdtclient.fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        ports:
        - containerPort: 6500
          name: http
        volumeMounts:
        - name: "{{ template "rdtclient.fullname" . }}-media"
          mountPath: "{{ .Values.volumes.downloads.pvc.mountPath }}"
        - name: "{{ template "rdtclient.fullname" . }}-config"
          mountPath: "{{ .Values.volumes.db.pvc.mountPath }}"
      volumes:
      - name: "{{ template "rdtclient.fullname" . }}-media"
        persistentVolumeClaim:
          claimName: "{{ .Values.volumes.downloads.pvc.name }}"
      - name: "{{ template "rdtclient.fullname" . }}-media"
        persistentVolumeClaim:
          claimName: "{{ .Values.volumes.db.pvc.name }}"
