apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rdtclient.fullname" . }}
  labels:
    {{- if eq .Values.volumes.downloads.pvc.storageClass "smb" }}
    smb-dependent: "true"
    {{- end }}
    {{- if eq .Values.volumes.downloads.pvc.storageClass "nfs" }}
    nfs-dependent: "true"
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    type: {{ .Values.strategy.type }}
    {{- if eq .Values.strategy.type "RollingUpdate" }}
    rollingUpdate:
      maxSurge: {{ .Values.strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.strategy.rollingUpdate.maxUnavailable }}
    {{- end }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ include "rdtclient.fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        ports:
        - containerPort: 6500
          name: http
        env:
        {{- with .Values.env }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        volumeMounts:
        - name: "{{ template "rdtclient.fullname" . }}-downloads"
          mountPath: "{{ .Values.volumes.downloads.pvc.mountPath }}"
        - name: "{{ template "rdtclient.fullname" . }}-config"
          mountPath: "{{ .Values.volumes.db.pvc.mountPath }}"
      volumes:
      - name: "{{ template "rdtclient.fullname" . }}-downloads"
        persistentVolumeClaim:
          claimName: {{ .Values.volumes.downloads.pvc.existingClaim }}
      - name: "{{ template "rdtclient.fullname" . }}-config"
        persistentVolumeClaim:
          claimName: "{{ template "rdtclient.fullname" . }}-config"