{{- if .Values.ingress.main.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "rdtclient.fullname" . }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.main.annotations.certManagerClusterIssuer }}
    hajimari.io/appName: {{ .Values.ingress.main.annotations.hajimariAppName }}
    hajimari.io/icon: {{ .Values.ingress.main.annotations.hajimariIcon }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.ingress.main.host }}
    http:
      paths:
      - path: {{ .Values.ingress.main.path }}
        pathType: {{ .Values.ingress.main.pathType }}
        backend:
          service:
            name: {{ include "rdtclient.fullname" . }}
            port:
              number: {{ .Values.service.port }}
  tls:
  - hosts:
    - {{ .Values.ingress.main.tls.host }}
    secretName: {{ .Values.ingress.main.tls.secretName }}
{{- end }}
