replicaCount: 1

image:
  repository: registry.lajas.tech/foodtrack
  tag: latest
  pullPolicy: Always

timezone: America/Chicago

secrets:
  DISCORD_BOT_TOKEN: true
  DISCORD_CHANNEL_ID: true
  GEOFENCE_LAT: true
  GEOFENCE_LON: true
  GEOFENCE_RADIUS: true
  HUE_BRIDGE_IP: true
  HUE_USER_TOKEN: true
  HUE_LIGHT_ID: true
  PHONE_NUMBER: true
  UBER_EATS_SESSION_ID: true

deploymentAnnotations:
  operator.1password.io/auto-restart: "true"
  operator.1password.io/item-path: "vaults/z3emsr5qi5xqk33wthv5fpmfqa/items/df5fpdjwattvubs6i6xglzjfpq"
  operator.1password.io/item-name: "foodtracker-secrets"