replicaCount: 1

image:
  repository: registry.lajas.tech/foodtrack
  tag: latest
  pullPolicy: Always

timezone: America/Chicago

opSecret:
  vault: "z3emsr5qi5xqk33wthv5fpmfqa"
  item: "df5fpdjwattvubs6i6xglzjfpq"
  secretName: "foodtracker-secrets"

secrets:
  DISCORD_BOT_TOKEN: true
  DISCORD_CHANNEL_ID: true
  GEOFENCE_LAT: true
  GEOFENCE_LON: true
  GEOFENCE_RADIUS: true
  HUE_BRIDGE_IP: true
  HUE_USER_TOKEN: true
  HUE_LIGHT_ID: true
  PHONE_NUMBER: true
  UBER_EATS_SESSION_ID: true

onePassword:
  enabled: true
