apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: smb
  annotations:
provisioner: smb.csi.k8s.io
parameters:
  source: '//plex.lajas.tech/downloads'
  csi.storage.k8s.io/provisioner-secret-name: "smbcreds"
  csi.storage.k8s.io/provisioner-secret-namespace: {{ .Release.Namespace }}
  csi.storage.k8s.io/node-stage-secret-name: "smbcreds"
  csi.storage.k8s.io/node-stage-secret-namespace: {{ .Release.Namespace }}
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1001
  - gid=1001
