apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "geysermc.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "geysermc.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "geysermc.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: geyser
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        workingDir: /app
        command: ["java", "-jar", "Geyser.jar"]
        volumeMounts:
        - name: geyser-config
          mountPath: /app
        env:
          - name: GEYSER_CONFIG_PATH
            value: "/app/geyser-config.yml"
      volumes:
      - name: geyser-config
        configMap:
          name: {{ .Release.Name }}-geyser-config
