apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "geysermc.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "geysermc.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "geysermc.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      initContainers:
      - name: init-config
        image: busybox
        command: ['/bin/sh', '-c']
        args:
        - |
          # Copy config.yaml from ConfigMap to the shared volume
          cp /config-map/config.yaml /app/config.yaml
        volumeMounts:
        - name: app-volume
          mountPath: /app
        - name: config-volume
          mountPath: /config-map
      containers:
      - name: geyser
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        workingDir: /app
        volumeMounts:
        - name: app-volume
          mountPath: /app
      volumes:
      - name: app-volume
        emptyDir: {}
      - name: config-volume
        configMap:
          name: {{ .Release.Name }}-geyser-config
