{{- if .Values.rbac.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "nas-dependency-operator.fullname" . }}-manager-role
  labels:
    {{- include "nas-dependency-operator.labels" . | nindent 4 }}
rules:
  # Core resources
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - ""
    resources:
      - namespaces
      - persistentvolumeclaims
      - persistentvolumes
    verbs:
      - get
      - list
      - watch
  # Workload resources
  - apiGroups:
      - apps
    resources:
      - daemonsets
      - deployments
      - statefulsets
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  # NASDependency CRD
  - apiGroups:
      - homelab.llajas.io
    resources:
      - nasdependencies
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - homelab.llajas.io
    resources:
      - nasdependencies/finalizers
    verbs:
      - update
  - apiGroups:
      - homelab.llajas.io
    resources:
      - nasdependencies/status
    verbs:
      - get
      - patch
      - update
  # ArgoCD integration (optional)
  {{- if .Values.argocd.enabled }}
  - apiGroups:
      - argoproj.io
    resources:
      - appprojects
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - argoproj.io
    resources:
      - applications
    verbs:
      - get
      - list
      - update
      - watch
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "nas-dependency-operator.fullname" . }}-manager-rolebinding
  labels:
    {{- include "nas-dependency-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "nas-dependency-operator.fullname" . }}-manager-role
subjects:
  - kind: ServiceAccount
    name: {{ include "nas-dependency-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
# Leader election role (namespace-scoped)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "nas-dependency-operator.fullname" . }}-leader-election-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nas-dependency-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "nas-dependency-operator.fullname" . }}-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nas-dependency-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "nas-dependency-operator.fullname" . }}-leader-election-role
subjects:
  - kind: ServiceAccount
    name: {{ include "nas-dependency-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
