{{- if .Values.notifyWebhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nas-dependency-operator.fullname" . }}-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nas-dependency-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ .Values.notifyWebhook.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "nas-dependency-operator.selectorLabels" . | nindent 4 }}
{{- end }}
