apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-home-assistant-config
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
  volumeMode: Filesystem
  volumeName: pvc-0e16563b-c2ce-4706-8788-4c31e670e6c8
