apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-home-assistant-config
  namespace: {{ include "home-assistant.namespace" . }}
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}
  volumeMode: Filesystem
  volumeName: pvc-0e16563b-c2ce-4706-8788-4c31e670e6c8
