{{- if and .Values.metrics.enabled .Values.metrics.prometheusRule.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "bjw-s.common.lib.chart.names.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "bjw-s.common.lib.chart.names.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- with .Values.metrics.prometheusRule.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  groups:
    - name: {{ include "bjw-s.common.lib.chart.names.fullname" . }}
      rules:
        - alert: HomeAssistantAbsent
          annotations:
            description: Home Assistant has disappeared from Prometheus service discovery.
            summary: Home Assistant is down.
          expr: |
            absent(up{job=~".*{{ include "bjw-s.common.lib.chart.names.fullname" . }}.*"} == 1)
          for: 5m
          labels:
            severity: critical
{{- end }}
