# metal/roles/detect_gpu/tasks/main.yml

- name: "Gather GPU information from hypervisor"
  shell: "lspci -nn | grep -i nvidia"
  register: gpu_list
  delegate_to: "{{ hypervisor_host }}"
  changed_when: false

- name: "Debug: Show the GPU lines we got"
  debug:
    var: gpu_list.stdout_lines

- name: "Initialize an empty gpu_map"
  set_fact:
    gpu_map: {}

###########################################################################
# Process each host in group 'metal' that has gpu_type defined           #
###########################################################################
- name: "Process GPU data for each GPU-enabled host"
  include_tasks: process_host.yml
  loop: "{{ groups['metal'] }}"
  loop_control:
    loop_var: host
  when: hostvars[host].gpu_type is defined

- name: "Debug final GPU map"
  debug:
    var: gpu_map

- name: "Save gpu_map to gpu_mapping for the next role"
  set_fact:
    gpu_mapping: "{{ gpu_map }}"
