tautulli:
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/appName: Tautulli
        hajimari.io/icon: movie-cog
      hosts:
        - host: &host tautulli.lajas.tech
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: tautulli-tls-certificate
          hosts:
            - *host
