tautulli:
  # Tautulli image and tag to use
  image:
    repository: linuxserver/tautulli
    tag: latest
  # Ingress configuration
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/appName: Tautulli
        hajimari.io/icon: movie-cog
      hosts:
        - host: &host tautulli.lajas.tech
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: tautulli-tls-certificate
          hosts:
            - *host
  # Configuration file persistence
  persistence:
    enabled: true
    existingClaim: tautulli-config-pvc
    mountPath: /config/config.ini
    subPath: config.ini
  # Database file persistence
  database:
    enabled: true
    existingClaim: tautulli-db-pvc
    mountPath: /config/tautulli.db
    subPath: tautulli.db
  service:
    port: 8181
