# Default values for rdtclient.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: rogerfar/rdtclient
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 2.0.79

replicaCount: 1

service:
  type: ClusterIP
  port: 6500

securityContext:
  runAsUser: 911
  runAsGroup: 911

ingress:
  main:
    enabled: true
    ingressclassName: nginx
    annotations:
      certManagerClusterIssuer: letsencrypt-prod
      hajimariAppName: RDT-Client
      hajimariIcon: cloud-download
    host: rdclient.lajas.tech
    path: /
    pathType: Prefix
    tls:
      secretName: rdtclient-tls-certificate
      host: rdclient.lajas.tech

volumes:
  downloads:
    pvc:
      mountPath: /data/downloads
      existingClaim: "plex-apps-cifs-plex-media"
      storageClass: smb
  db:
    pvc:
      name: db-pvc
      mountPath: /data/db
      accessModes: ReadWriteOnce
      storageSize: 1Gi
