{{- if .Values.unraidHttp.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.unraidHttp.name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.unraidHttp.service.port }}
    targetPort: {{ .Values.unraidHttp.service.targetPort }}
    protocol: TCP

---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Values.unraidHttp.name }}
  namespace: {{ .Release.Namespace }}
subsets:
- addresses:
  - ip: {{ .Values.unraidHttp.endpoints.ip }}
  ports:
  - port: {{ .Values.unraidHttp.service.port }}

{{- if .Values.unraidHttp.ingress.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.unraidHttp.ingress.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
{{ toYaml .Values.unraidHttp.ingress.annotations | indent 4 }}
spec:
  parentRefs:
  - name: public-gateway
    namespace: kube-system
    sectionName: https
  hostnames:
  - {{ .Values.unraidHttp.ingress.host | quote }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: {{ .Values.unraidHttp.name }}
      port: {{ .Values.unraidHttp.service.port }}
{{- end }}
{{- end }}
