replicaCount: 1

image:
  repository: deinfreu/hytale-server
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

deploymentAnnotations: {}
deploymentLabels: {}
deploymentStrategy: Recreate

podAnnotations: {}
podLabels: {}

serviceAnnotations:
  metallb.universe.tf/allow-shared-ip: "hytale"
serviceLabels: {}

hytaleServer:
  serviceType: LoadBalancer
  servicePort: 5520
  nodePort:
  clusterIP:
  loadBalancerIP: 10.137.0.250
  loadBalancerClass:
  loadBalancerSourceRanges: []
  externalTrafficPolicy: Cluster
  externalIPs: []
  extraServiceSpec: {}

  env:
    SERVER_IP: "0.0.0.0"
    SERVER_PORT: "5520"
    TZ: "America/Chicago"
    DEBUG: "FALSE"
    PROD: "TRUE"
    JAVA_ARGS: "-Xms4G -Xmx6G"
    HYTALE_SERVER_NAME: "Adventure Time SHP"
    HYTALE_MOTD: "You are now entering the world of Adventure Time! Have fun, be kind, and explore!"
    HYTALE_CACHE: "TRUE"

envFrom:
  - secretRef:
      name: hytale-secrets

persistence:
  labels: {}
  annotations: {}
  storageClass: longhorn
  dataDir:
    enabled: true
    Size: 10Gi
    accessModes:
      - ReadWriteOnce
    existingClaim:
    subPath:

machineId:
  secretName: hytale-secrets
  secretKey: machine-id
  filePath: /etc/machine-id

opSecrets:
  vault: "z3emsr5qi5xqk33wthv5fpmfqa"
  secrets:
    - name: hytale-secrets
      item: "yxrm633gewlzmcuqcg5z2onyya"
      secretName: "hytale-secrets"
    - name: hytale-backup-credentials
      item: "hrptxjxgsvdd3dv5eqatmbjhrq"
      secretName: "hytale-backup-credentials"

resources:
  requests:
    cpu: "2000m"
    memory: "6Gi"
  limits:
    cpu: "4000m"
    memory: "8Gi"

backup:
  enabled: true
  env:
    HYTALE_BACKUP: "TRUE"
    HYTALE_BACKUP_DIR: "/home/container/backups"
    HYTALE_BACKUP_FREQUENCY: "60"
    HYTALE_BACKUP_MAX_COUNT: "48"
  persistence:
    storageType: smb
    backupDir:
      Size: 20Gi
    smb:
      server: "//nas-01.storage.lajas.tech/"
      shareName: "hytale_world_backup"
      secret: hytale-backup-credentials

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  fsGroupChangePolicy: OnRootMismatch
securityContext:
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
