{{- if .Values.sshLoadBalancer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-ssh-lb"
  namespace: "{{ .Release.Namespace }}"
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.sshLoadBalancer.hostnames | quote }}
{{- if .Values.sshLoadBalancer.ip }}
    lbipam.cilium.io/ips: {{ .Values.sshLoadBalancer.ip | quote }}
{{- if .Values.sshLoadBalancer.sharingKey }}
    lbipam.cilium.io/sharing-key: {{ .Values.sshLoadBalancer.sharingKey | quote }}
{{- end }}
{{- if .Values.sshLoadBalancer.sharingCrossNamespace }}
    lbipam.cilium.io/sharing-cross-namespace: {{ .Values.sshLoadBalancer.sharingCrossNamespace | quote }}
{{- end }}
{{- end }}
spec:
  type: LoadBalancer
  ports:
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: 2222
  selector:
    app.kubernetes.io/name: gitea
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
