apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea-webhook-secret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  data:
    - secretKey: token
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /tekton/webhook
        property: token
