apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "63Ti"
  storageClassName: nfs
