{{- if not .Values.global.sharedStorage.media.existingClaim }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-media
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.global.sharedStorage.media.size }}
  storageClassName: {{ .Values.global.sharedStorage.media.storageClass }}
  {{- if .Values.global.sharedStorage.media.volumeName }}
  volumeName: {{ .Values.global.sharedStorage.media.volumeName }}
  {{- else }}
  volumeName: {{ .Release.Name }}-media
  {{- end }}
{{- end }}
