{{- if .Values.pms.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-pms
  labels:
    app.kubernetes.io/service: {{ .Release.Name }}-pms
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: pms
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version }}
    {{- with .Values.pms.serviceConfig.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.pms.serviceConfig.annotations | nindent 4 }}
spec:
  type: LoadBalancer
  {{- if .Values.pms.serviceConfig.loadBalancerClass }}
  loadBalancerClass: {{ .Values.pms.serviceConfig.loadBalancerClass | quote }}
  {{- end }}
  loadBalancerIP: {{ .Values.pms.serviceConfig.loadBalancerIP | quote }}
  externalTrafficPolicy: {{ .Values.pms.serviceConfig.externalTrafficPolicy }}
  ports:
    - port: {{ .Values.pms.config.port | default 32400 }}
      targetPort: {{ .Values.pms.config.port | default 32400 }}
      protocol: TCP
      name: plex-web
      appProtocol: http
    - port: {{ .Values.pms.config.relayPort | default 32499 }}
      targetPort: {{ .Values.pms.config.relayPort | default 32499 }}
      protocol: TCP
      name: relay
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: pms
{{- end }}
