---
apiVersion: v2
appVersion: 2023.8.4
description: Home Assistant
name: home-assistant
version: 14.0.0
kubeVersion: ">=1.16.0-0"
keywords:
  - home-assistant
  - hass
  - homeassistant
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/home-assistant
icon: https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Home_Assistant_Logo.svg/519px-Home_Assistant_Logo.svg.png
sources:
  - https://github.com/home-assistant/home-assistant
  - https://github.com/cdr/code-server
  - https://github.com/k8s-at-home/charts/tree/master/charts/stable/home-assistant
maintainers:
  - name: billimek
    email: jeff@billimek.com
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
  - name: postgresql
    version: 15.2.5
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: mariadb
    version: 16.4.0
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
  - name: influxdb
    version: 6.0.2
    repository: https://charts.bitnami.com/bitnami
    condition: influxdb.enabled
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 4.5.2
