---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: udm-pro
  namespace: metallb-system
spec:
  myASN: 64513
  peerASN: 64512
  peerAddress: 10.137.0.1
  passive: true
  nodeSelectors:
    - matchExpressions:
        - key: node-role.kubernetes.io/master
          operator: DoesNotExist
