apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "byparr.fullname" . }}-config
spec:
  accessModes:
    - {{ .Values.volumes.db.pvc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.volumes.db.pvc.storageSize }}
