apiVersion: v1
kind: Service
metadata:
  name: {{ include "byparr.fullname" . }}
  labels:
    {{- include "byparr.labels" . | nindent 4 }}
  annotations:
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: {{ include "byparr.fullname" . }}
  selector:
    app.kubernetes.io/name: {{ include "byparr.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
