apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Values.tmuxSSH.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  itemPath: "vaults/{{ .Values.tmuxSSH.vault }}/items/{{ .Values.tmuxSSH.item }}"
