apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opencode-ghq
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - {{ .Values.workspace.accessMode }}
  resources:
    requests:
      storage: {{ .Values.workspace.capacity }}
  storageClassName: {{ .Values.workspace.storageClass }}
  volumeMode: Filesystem
  volumeName: opencode-ghq
