{{- range $index, $externalSecret := .Values.externalSecrets }}
{{- if $index }}
---
{{- end }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $externalSecret.name }}
spec:
  secretStoreRef:
    kind: {{ $externalSecret.secretStoreRef.kind }}
    name: {{ $externalSecret.secretStoreRef.name }}
  target:
    template:
      type: Opaque
  data:
  {{- range $externalSecret.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        conversionStrategy: {{ .remoteRef.conversionStrategy }}
        decodingStrategy: {{ .remoteRef.decodingStrategy }}
        key: {{ .remoteRef.key }}
        metadataPolicy: {{ .remoteRef.metadataPolicy }}
        property: {{ .remoteRef.property }}
  {{- end }}
{{- end }}
