kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: "homebridge"
  namespace: {{ $.Values.namespaceOverride }}

spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: homebridge
                port:
                  number: {{ .Values.service.port }}
