apiVersion: v1
kind: Service
metadata:
  name: homebridge
  namespace: {{ $.Values.namespaceOverride  }}
spec:
  selector:
    app.kubernetes.io/instance: homebridge
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
