apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minecraft-player-secrets
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    template:
      type: Opaque
  data:
  - secretKey: WHITELIST
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: minecraft.players
      property: WHITELIST
  - secretKey: OPS
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: minecraft.players
      property: OPS
  - secretKey: RCON_PASSWORD
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: minecraft.rcon
      property: RCON
