#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

controller:
  labels:
    nfs-dependent: "true"

image:
  # -- image repository
  repository: lancachenet/monolithic
  # -- image tag
  tag: latest
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables. See more environment variables in the [LanCache Monolithic documentation](https://lancache.net/docs/containers/monolithic/variables/).
# @default -- See below
env:
  # -- Set the container timezone
  TZ: America/Chicago
  # UPSTREAM_DNS:
  # CACHE_MEM_SIZE:
  # CACHE_DISK_SIZE:
  # CACHE_MAX_AGE:

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    type: LoadBalancer
    loadBalancerIP: 10.137.0.229
    ports:
      http:
        port: 80
      https:
        enabled: true
        port: 443
  dns:
    enabled: true
    type: LoadBalancer
    loadBalancerIP: 10.137.0.230
    ports:
      dns:
        port: 53

# -- LanCache uses custom upstream nameservers, overridable with the `UPSTREAM_DNS` variable.
dnsPolicy: None
dnsConfig:
  nameservers:
    - 10.137.0.253

dns:
  # -- Enable and configure LanCache DNS sidecar and service.
  # @default -- See values.yaml
  enabled: true
  gameServices:
    - steam
    - origin
    - uplay
    - battlenet
    - etc
  # -- environment variables. See more environment variables in the [LanCache DNS documentation](https://lancache.net/docs/containers/dns/variables/).
  # Most variables are inherited from the top-level `env`. `LANCACHE_IP` is auto-generated from the `loadBalancerIP` of the `main` service if specified.
  env: {}
  image:
    # -- image repository
    repository: lancachenet/lancache-dns
    # -- image tag
    tag: latest
    # -- image pull policy
    pullPolicy: IfNotPresent

probes:
  readiness:
    custom: true
    spec:
      httpGet:
        path: /lancache-heartbeat
        port: 80
  liveness:
    custom: true
    spec:
      httpGet:
        path: /lancache-heartbeat
        port: 80
  startup:
    custom: true
    spec:
      httpGet:
        path: /lancache-heartbeat
        port: 80

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  data:
    enabled: true
    existingClaim: lancache-data-cache-pvc
    mountPath: /data/cache
    accessMode: ReadWriteOnce
    driver: smb.csi.k8s.io
    storageClassName: smb
    size: 1Ti
    share:
      path: lancache/
      server: //nas-01.storage.lajas.tech/
    reclaimPolicy: Retain
    volumeMode: Filesystem
    secret:
      secretName: cifs.creds.lancache
      vault: "z3emsr5qi5xqk33wthv5fpmfqa"
      items: "c7ec7bt633qs2crad7ga3bb4am"
  logs:
    enabled: true
    mountPath: /data/logs
    accessMode: ReadWriteOnce
    size: 2Gi

# -- The official LanCache image is only available for x86_64.
nodeSelector:
  kubernetes.io/arch: amd64

additionalContainers:
  monolithic-logs:
    image: busybox
    args: [/bin/sh, -c, 'tail -n1 -F /data/logs/access.log']
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - name: logs
        mountPath: /data/logs
