apiVersion: apps/v1
{{- $podAnnotations := .Values.podAnnotations }}
{{- $secretAnnotation := dict "checksum/config" (include (print $.Template.BasePath "/configmap.yaml") . | sha256sum) }}
{{- $podAnnotations := merge $podAnnotations $secretAnnotation }}
kind: Deployment
metadata:
  name: {{ include "tautulli.fullname" . }}
  {{- if .Values.deploymentAnnotations }}
  annotations:
    {{- range $key, $value := .Values.deploymentAnnotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  labels:
{{ include "tautulli.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
{{- if .Values.strategy }}
  strategy:
{{ toYaml .Values.strategy | indent 4 }}
{{ if eq .Values.strategy.type "Recreate" }}
    rollingUpdate: null
{{- end }}
{{- end }}
  selector:
    matchLabels:
      {{- include "tautulli.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tautulli.selectorLabels" . | nindent 8 }}
      {{- if $podAnnotations }}
      annotations:
        {{- range $key, $value := $podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "tautulli.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.dnsConfig }}
      dnsConfig:
        {{- toYaml .Values.dnsConfig | nindent 8 }}
      {{- end }}
{{- if or .Values.persistence.enabled .Values.getGeoCity.enabled }}
      initContainers:
{{- if .Values.persistence.enabled }}
        - name: init-chown-data
          image: "{{ .Values.chownDataImage.repository }}:{{ .Values.chownDataImage.tag }}"
          imagePullPolicy: {{ .Values.chownDataImage.pullPolicy }}
          securityContext:
            runAsUser: 0
          command: ["chown", "-R", "{{ .Values.tautulli.uid }}:{{ .Values.tautulli.gid }}", "/config"]
          volumeMounts:
            - name: tautulli-config
              mountPath: /config
{{- end }}
{{- if .Values.getGeoCity.enabled }}
        - name: get-city-db
          image: "{{ .Values.getGeoCity.image.repository }}:{{ .Values.getGeoCity.image.tag }}"
          imagePullPolicy: {{ .Values.getGeoCity.image.pullPolicy }}
          env:
            - name: GEOIP_CONFIG_FILE
              value: "/etc/geoipupdater/GeoIP.conf"
          volumeMounts:
            - name: tautulli-config
              mountPath: /usr/local/share/GeoIP
            - name: geoip-config
              mountPath: /etc/geoipupdater/
{{- end }}
{{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ tpl .Values.image.tag . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PGID
              value: {{ .Values.tautulli.gid | quote }}
            - name: PUID
              value: {{ .Values.tautulli.uid | quote }}
            - name: TZ
              value: {{ .Values.tautulli.tz | quote }}
          ports:
            - name: http
              containerPort: 8181
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /auth/login
              port: http
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
          readinessProbe:
            httpGet:
              path: /auth/login
              port: http
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
{{- if semverCompare ">=1.16-0" .Capabilities.KubeVersion.GitVersion }}
          startupProbe:
            httpGet:
              path: /auth/login
              port: http
            initialDelaySeconds: {{ .Values.probes.startup.initialDelaySeconds }}
            failureThreshold: {{ .Values.probes.startup.failureThreshold }}
            periodSeconds: {{ .Values.probes.startup.periodSeconds }}
{{- end }}
          volumeMounts:
          - name: tautulli-config
            mountPath: /config
          - name: etc-timezone
            mountPath: /etc/timezone:ro
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: etc-timezone
        hostPath:
          path: /etc/localtime
      {{- if .Values.getGeoCity.enabled }}
      - name: geoip-config
        configMap:
          name: {{ template "tautulli.fullname" . }}
      {{- end }}
      - name: tautulli-config
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}{{ template "tautulli.fullname" . }}{{- end }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
