! Minimal BGP config for UDM-Pro
router bgp 64512
 bgp router-id 10.137.0.1
 maximum-paths 8
 !
 neighbor K8S peer-group
 neighbor K8S remote-as 64513
 neighbor 10.137.0.10 peer-group K8S
 neighbor 10.137.0.11 peer-group K8S
 neighbor 10.137.0.12 peer-group K8S
 !
 neighbor K8S-SVC peer-group
 neighbor K8S-SVC remote-as 64514
 neighbor 10.137.0.10 peer-group K8S-SVC
 neighbor 10.137.0.11 peer-group K8S-SVC
 neighbor 10.137.0.12 peer-group K8S-SVC
 neighbor 10.137.0.13 peer-group K8S-SVC
 neighbor 10.137.0.14 peer-group K8S-SVC
 neighbor 10.137.0.15 peer-group K8S-SVC
 neighbor 10.137.0.16 peer-group K8S-SVC
 neighbor 10.137.0.17 peer-group K8S-SVC
 !
 address-family ipv4 unicast
  redistribute connected
  neighbor K8S activate
  neighbor K8S route-map ALLOW-ALL in
  neighbor K8S route-map ALLOW-ALL out
  neighbor K8S next-hop-self
  neighbor K8S-SVC activate
  neighbor K8S-SVC route-map ALLOW-ALL in
  neighbor K8S-SVC route-map ALLOW-ALL out
  neighbor K8S-SVC soft-reconfiguration inbound
 exit-address-family
!
route-map ALLOW-ALL permit 10
!
line vty
!
