apiVersion: v2
name: metallb-system
version: 0.0.0
description: MetalLB controller for dedicated service VIPs
dependencies:
  - name: metallb
    version: 0.15.3
    repository: https://metallb.github.io/metallb/
