- name: Send Wake-on-LAN magic packets
  community.general.wakeonlan:
    mac: "{{ mac }}"
  delegate_to: localhost

- name: Send Wake-On-LAN magic packets to VM's
  community.general.wakeonlan:
    mac: "{{ mac }}"
    port: 9
    broadcast: {{ hypervisor_address }}
  delegate_to: localhost
  when: virtual | default(false)

- name: Wait for the machines to come online
  ansible.builtin.wait_for_connection:
    timeout: 1000
