# Image settings
image:
  repository: scyto/unifibrowser
  pullPolicy: IfNotPresent
  tag: latest

# Replica count
replicaCount: 1

# Namespace override
namespaceOverride: ""

# Service settings
service:
  type: ClusterIP
  port: 8000

# Security context settings
securityContext:
  runAsUser: 1000
  runAsGroup: 1000

# External secrets settings
externalSecrets:
  name: unifibrowser-secrets

# Other non-sensitive settings
port: 443
displayname: "My Unifi Site"
noapibrowserauth: 0

ingress:
  main:
    enabled: true
    ingressclassName: nginx
    annotations:
      certManagerClusterIssuer: letsencrypt-prod
    host: unifi-browser.falconpunch.org
    path: /
    pathType: Prefix
    tls:
      secretName: unifibrowser-tls
      host: unifi-browser.falconpunch.org
