# Image settings
image:
  repository: scyto/unifibrowser
  pullPolicy: IfNotPresent
  tag: latest

# Replica count
replicaCount: 1

# Namespace override
namespaceOverride: ""

# Service settings
service:
  type: ClusterIP
  port: 8000

# Security context settings
securityContext:
  runAsUser: 1000
  runAsGroup: 1000

# External secrets settings
externalSecrets:
  name: &secret unifibrowser-secrets

# Deployment Annotations
deploymentAnnotations:
  operator.1password.io/item-path: "vaults/z3emsr5qi5xqk33wthv5fpmfqa/items/tctuxkhkkgfsprh2jpoanop5ku"
  operator.1password.io/item-name: *secret

# Other non-sensitive settings
port: 443
displayname: "My Unifi Site"
noapibrowserauth: 0

ingress:
  main:
    enabled: true
    ingressclassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    host: &host unifi-browser.lajas.tech
    path: /
    pathType: Prefix
    tls:
      secretName: unifibrowser-tls
      host: *host
