apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.connect.credentialsName }}
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
    name: {{ .Values.externalSecret.secretStoreRef.name }}
  target:
    template:
      type: Opaque
  data:
  {{- range .Values.externalSecret.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        conversionStrategy: {{ .remoteRef.conversionStrategy }}
        decodingStrategy: {{ .remoteRef.decodingStrategy }}
        key: {{ .remoteRef.key }}
        metadataPolicy: {{ .remoteRef.metadataPolicy }}
        property: {{ .remoteRef.property }}
  {{- end }}
