# === Add any number of metrics exporters here ===
exporters:
  - name: unraid-node-exporter
    ip: 10.33.0.5
    port: 9100
    portName: metrics
    interval: 30s
    labels:
      source: unraid
    serviceMonitor:
      enabled: true
      releaseLabel: prometheus

  - name: mtsilver-node-exporter
    ip: 10.137.0.151
    port: 9100
    portName: metrics
    interval: 30s
    labels:
      source: cloudkey
      role: edge-appliance
    serviceMonitor:
      enabled: true
      releaseLabel: prometheus

  - name: mtsilver-fail2ban
    ip: 10.137.0.151
    port: 9191
    portName: metrics
    interval: 30s
    labels:
      source: cloudkey
      role: edge-appliance
    serviceMonitor:
      enabled: true
      releaseLabel: prometheus

# === Optional Unraid HTTP exposure with Ingress ===
unraidHttp:
  enabled: true
  name: unraid-http
  service:
    port: 8080
    targetPort: 80
  endpoints:
    ip: 10.33.0.5
  ingress:
    enabled: true
    name: unraid
    className: nginx
    host: unraid.lajas.tech
    tlsSecret: unraid-tls
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      nginx.ingress.kubernetes.io/proxy-ssl-verify: "off"
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
      external-dns.alpha.kubernetes.io/target: "homelab-tunnel.lajas.tech"
